services:
  qcm-generator:
    image: ghcr.io/${GITHUB_REPOSITORY:-toby-bro/latex_qcm_generator}:main
    pull_policy: always
    container_name: qcm-generator
    network_mode: bridge
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./qcm_generator/:/app/qcm_generator/
    environment:
      - FLASK_APP=qcm_generator.main_flask
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./qcm_generator/
          target: /app/qcm_generator/
          ignore:
            - __pycache__/
            - "*.pyc"
            - subjects/
            - questions.txt
            - debug.log
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: index.html
